name: Deploy to Live

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create local changes
        run: |
          yarn install
          yarn run build
      - name: Commit and push local changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.2
        with:
          commit_message: Apply theme changes
      - name: pull repo from production server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd kuesters.net
            git pull
